window:
  position:
    x: 0
    y: 0
  padding:
    x: 2
    y: 2
  dynamic_padding: true
  decorations: full
  dynamic_title: true

selection:
  semantic_escape_chars: ",â”‚`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

mouse:
  hints:
    launcher:
      program: open
    modifiers: Command

font:
  normal:
    family: JetBrains Mono
    style: Regular
  bold:
    family: JetBrains Mono
    style: Bold
  italic:
    family: JetBrains Mono
    style: Italic
  bold_italic:
    family: JetBrains Mono
    style: Bold Italic
  size: 13.0
  use_thin_strokes: true
draw_bold_text_with_bright_colors: true

schemes:
  gruvbox: &gruvbox
    primary:
      background: '0x1d2021'
      foreground: '0xd4be98'
    normal:
      black:   '0x1D2021'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      aqua:    '0x89b482'
      white:   '0xd4be98'
    bright:
      black:   '0x17191a'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      aqua:    '0x89b482'
      white:   '0xd4be98'
    indexed_colors:
      - { index: 16, color: '0xe78a4e' }
      - { index: 17, color: '0xc14a4a' }

key_bindings:
  - { key: F,  mods: Alt, chars: "\x1bf" }
  - { key: B,  mods: Alt, chars: "\x1bb" }
  - { key: D,  mods: Alt, chars: "\x1bd" }

colors: *gruvbox
